//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusorWpf.ServiceData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogPass", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class LogPass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusorWpf.ServiceData.Access AccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSubEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HWIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] _CodesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusorWpf.ServiceData.Access Access {
            get {
                return this.AccessField;
            }
            set {
                if ((this.AccessField.Equals(value) != true)) {
                    this.AccessField = value;
                    this.RaisePropertyChanged("Access");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codes {
            get {
                return this.CodesField;
            }
            set {
                if ((object.ReferenceEquals(this.CodesField, value) != true)) {
                    this.CodesField = value;
                    this.RaisePropertyChanged("Codes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSubEnd {
            get {
                return this.DateSubEndField;
            }
            set {
                if ((this.DateSubEndField.Equals(value) != true)) {
                    this.DateSubEndField = value;
                    this.RaisePropertyChanged("DateSubEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HWID {
            get {
                return this.HWIDField;
            }
            set {
                if ((object.ReferenceEquals(this.HWIDField, value) != true)) {
                    this.HWIDField = value;
                    this.RaisePropertyChanged("HWID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretKey {
            get {
                return this.SecretKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretKeyField, value) != true)) {
                    this.SecretKeyField = value;
                    this.RaisePropertyChanged("SecretKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] _Codes {
            get {
                return this._CodesField;
            }
            set {
                if ((object.ReferenceEquals(this._CodesField, value) != true)) {
                    this._CodesField = value;
                    this.RaisePropertyChanged("_Codes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Access", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    public enum Access : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Helper = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendIndfo", Namespace="http://schemas.datacontract.org/2004/07/WCFService2")]
    [System.SerializableAttribute()]
    public partial class SendIndfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSubEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SeekerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusorWpf.ServiceData.User[] UsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusorWpf.ServiceData.LogPass[] passesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSubEnd {
            get {
                return this.DateSubEndField;
            }
            set {
                if ((this.DateSubEndField.Equals(value) != true)) {
                    this.DateSubEndField = value;
                    this.RaisePropertyChanged("DateSubEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Seeker {
            get {
                return this.SeekerField;
            }
            set {
                if ((this.SeekerField.Equals(value) != true)) {
                    this.SeekerField = value;
                    this.RaisePropertyChanged("Seeker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusorWpf.ServiceData.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusorWpf.ServiceData.LogPass[] passes {
            get {
                return this.passesField;
            }
            set {
                if ((object.ReferenceEquals(this.passesField, value) != true)) {
                    this.passesField = value;
                    this.RaisePropertyChanged("passes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NicknameSendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nickname {
            get {
                return this.NicknameField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameField, value) != true)) {
                    this.NicknameField = value;
                    this.RaisePropertyChanged("Nickname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NicknameSended {
            get {
                return this.NicknameSendedField;
            }
            set {
                if ((object.ReferenceEquals(this.NicknameSendedField, value) != true)) {
                    this.NicknameSendedField = value;
                    this.RaisePropertyChanged("NicknameSended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="logger", Namespace="http://schemas.datacontract.org/2004/07/WCFService2")]
    [System.SerializableAttribute()]
    public partial class logger : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusorWpf.ServiceData.Helper HelperField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusorWpf.ServiceData.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MusorWpf.ServiceData.LogPass logPassField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusorWpf.ServiceData.Helper Helper {
            get {
                return this.HelperField;
            }
            set {
                if ((object.ReferenceEquals(this.HelperField, value) != true)) {
                    this.HelperField = value;
                    this.RaisePropertyChanged("Helper");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusorWpf.ServiceData.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public MusorWpf.ServiceData.LogPass logPass {
            get {
                return this.logPassField;
            }
            set {
                if ((object.ReferenceEquals(this.logPassField, value) != true)) {
                    this.logPassField = value;
                    this.RaisePropertyChanged("logPass");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Helper", Namespace="http://schemas.datacontract.org/2004/07/WCFService2")]
    [System.SerializableAttribute()]
    public partial class Helper : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceData.IServiceData")]
    public interface IServiceData {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/Login", ReplyAction="http://tempuri.org/IServiceData/LoginResponse")]
        MusorWpf.ServiceData.SendIndfo Login(MusorWpf.ServiceData.LogPass logPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/Login", ReplyAction="http://tempuri.org/IServiceData/LoginResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> LoginAsync(MusorWpf.ServiceData.LogPass logPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetCodes", ReplyAction="http://tempuri.org/IServiceData/GetCodesResponse")]
        MusorWpf.ServiceData.SendIndfo GetCodes(MusorWpf.ServiceData.LogPass logPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetCodes", ReplyAction="http://tempuri.org/IServiceData/GetCodesResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetCodesAsync(MusorWpf.ServiceData.LogPass logPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteUser", ReplyAction="http://tempuri.org/IServiceData/DeleteUserResponse")]
        void DeleteUser(MusorWpf.ServiceData.LogPass logPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteUser", ReplyAction="http://tempuri.org/IServiceData/DeleteUserResponse")]
        System.Threading.Tasks.Task DeleteUserAsync(MusorWpf.ServiceData.LogPass logPass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/SendNickname", ReplyAction="http://tempuri.org/IServiceData/SendNicknameResponse")]
        MusorWpf.ServiceData.SendIndfo SendNickname(MusorWpf.ServiceData.logger user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/SendNickname", ReplyAction="http://tempuri.org/IServiceData/SendNicknameResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> SendNicknameAsync(MusorWpf.ServiceData.logger user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetListNickname", ReplyAction="http://tempuri.org/IServiceData/GetListNicknameResponse")]
        MusorWpf.ServiceData.SendIndfo GetListNickname(MusorWpf.ServiceData.logger getlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetListNickname", ReplyAction="http://tempuri.org/IServiceData/GetListNicknameResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetListNicknameAsync(MusorWpf.ServiceData.logger getlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/CreateHelperAcc", ReplyAction="http://tempuri.org/IServiceData/CreateHelperAccResponse")]
        MusorWpf.ServiceData.SendIndfo CreateHelperAcc(MusorWpf.ServiceData.logger chelper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/CreateHelperAcc", ReplyAction="http://tempuri.org/IServiceData/CreateHelperAccResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> CreateHelperAccAsync(MusorWpf.ServiceData.logger chelper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/ChangeBalance", ReplyAction="http://tempuri.org/IServiceData/ChangeBalanceResponse")]
        MusorWpf.ServiceData.SendIndfo ChangeBalance(MusorWpf.ServiceData.logger AccBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/ChangeBalance", ReplyAction="http://tempuri.org/IServiceData/ChangeBalanceResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> ChangeBalanceAsync(MusorWpf.ServiceData.logger AccBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetBalance", ReplyAction="http://tempuri.org/IServiceData/GetBalanceResponse")]
        MusorWpf.ServiceData.SendIndfo GetBalance(MusorWpf.ServiceData.logger AccBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetBalance", ReplyAction="http://tempuri.org/IServiceData/GetBalanceResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetBalanceAsync(MusorWpf.ServiceData.logger AccBalance);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddCodetoHelper", ReplyAction="http://tempuri.org/IServiceData/AddCodetoHelperResponse")]
        MusorWpf.ServiceData.SendIndfo AddCodetoHelper(MusorWpf.ServiceData.logger Addhelper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/AddCodetoHelper", ReplyAction="http://tempuri.org/IServiceData/AddCodetoHelperResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> AddCodetoHelperAsync(MusorWpf.ServiceData.logger Addhelper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetDate", ReplyAction="http://tempuri.org/IServiceData/GetDateResponse")]
        MusorWpf.ServiceData.SendIndfo GetDate(MusorWpf.ServiceData.logger Dhelper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetDate", ReplyAction="http://tempuri.org/IServiceData/GetDateResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetDateAsync(MusorWpf.ServiceData.logger Dhelper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetHelpers", ReplyAction="http://tempuri.org/IServiceData/GetHelpersResponse")]
        MusorWpf.ServiceData.SendIndfo GetHelpers(MusorWpf.ServiceData.logger helper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/GetHelpers", ReplyAction="http://tempuri.org/IServiceData/GetHelpersResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetHelpersAsync(MusorWpf.ServiceData.logger helper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteHelperAcc", ReplyAction="http://tempuri.org/IServiceData/DeleteHelperAccResponse")]
        MusorWpf.ServiceData.SendIndfo DeleteHelperAcc(MusorWpf.ServiceData.logger helper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/DeleteHelperAcc", ReplyAction="http://tempuri.org/IServiceData/DeleteHelperAccResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> DeleteHelperAccAsync(MusorWpf.ServiceData.logger helper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/RemoveCodeHelper", ReplyAction="http://tempuri.org/IServiceData/RemoveCodeHelperResponse")]
        MusorWpf.ServiceData.SendIndfo RemoveCodeHelper(MusorWpf.ServiceData.logger helper);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceData/RemoveCodeHelper", ReplyAction="http://tempuri.org/IServiceData/RemoveCodeHelperResponse")]
        System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> RemoveCodeHelperAsync(MusorWpf.ServiceData.logger helper);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceDataChannel : MusorWpf.ServiceData.IServiceData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDataClient : System.ServiceModel.ClientBase<MusorWpf.ServiceData.IServiceData>, MusorWpf.ServiceData.IServiceData {
        
        public ServiceDataClient() {
        }
        
        public ServiceDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MusorWpf.ServiceData.SendIndfo Login(MusorWpf.ServiceData.LogPass logPass) {
            return base.Channel.Login(logPass);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> LoginAsync(MusorWpf.ServiceData.LogPass logPass) {
            return base.Channel.LoginAsync(logPass);
        }
        
        public MusorWpf.ServiceData.SendIndfo GetCodes(MusorWpf.ServiceData.LogPass logPass) {
            return base.Channel.GetCodes(logPass);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetCodesAsync(MusorWpf.ServiceData.LogPass logPass) {
            return base.Channel.GetCodesAsync(logPass);
        }
        
        public void DeleteUser(MusorWpf.ServiceData.LogPass logPass) {
            base.Channel.DeleteUser(logPass);
        }
        
        public System.Threading.Tasks.Task DeleteUserAsync(MusorWpf.ServiceData.LogPass logPass) {
            return base.Channel.DeleteUserAsync(logPass);
        }
        
        public MusorWpf.ServiceData.SendIndfo SendNickname(MusorWpf.ServiceData.logger user) {
            return base.Channel.SendNickname(user);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> SendNicknameAsync(MusorWpf.ServiceData.logger user) {
            return base.Channel.SendNicknameAsync(user);
        }
        
        public MusorWpf.ServiceData.SendIndfo GetListNickname(MusorWpf.ServiceData.logger getlist) {
            return base.Channel.GetListNickname(getlist);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetListNicknameAsync(MusorWpf.ServiceData.logger getlist) {
            return base.Channel.GetListNicknameAsync(getlist);
        }
        
        public MusorWpf.ServiceData.SendIndfo CreateHelperAcc(MusorWpf.ServiceData.logger chelper) {
            return base.Channel.CreateHelperAcc(chelper);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> CreateHelperAccAsync(MusorWpf.ServiceData.logger chelper) {
            return base.Channel.CreateHelperAccAsync(chelper);
        }
        
        public MusorWpf.ServiceData.SendIndfo ChangeBalance(MusorWpf.ServiceData.logger AccBalance) {
            return base.Channel.ChangeBalance(AccBalance);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> ChangeBalanceAsync(MusorWpf.ServiceData.logger AccBalance) {
            return base.Channel.ChangeBalanceAsync(AccBalance);
        }
        
        public MusorWpf.ServiceData.SendIndfo GetBalance(MusorWpf.ServiceData.logger AccBalance) {
            return base.Channel.GetBalance(AccBalance);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetBalanceAsync(MusorWpf.ServiceData.logger AccBalance) {
            return base.Channel.GetBalanceAsync(AccBalance);
        }
        
        public MusorWpf.ServiceData.SendIndfo AddCodetoHelper(MusorWpf.ServiceData.logger Addhelper) {
            return base.Channel.AddCodetoHelper(Addhelper);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> AddCodetoHelperAsync(MusorWpf.ServiceData.logger Addhelper) {
            return base.Channel.AddCodetoHelperAsync(Addhelper);
        }
        
        public MusorWpf.ServiceData.SendIndfo GetDate(MusorWpf.ServiceData.logger Dhelper) {
            return base.Channel.GetDate(Dhelper);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetDateAsync(MusorWpf.ServiceData.logger Dhelper) {
            return base.Channel.GetDateAsync(Dhelper);
        }
        
        public MusorWpf.ServiceData.SendIndfo GetHelpers(MusorWpf.ServiceData.logger helper) {
            return base.Channel.GetHelpers(helper);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> GetHelpersAsync(MusorWpf.ServiceData.logger helper) {
            return base.Channel.GetHelpersAsync(helper);
        }
        
        public MusorWpf.ServiceData.SendIndfo DeleteHelperAcc(MusorWpf.ServiceData.logger helper) {
            return base.Channel.DeleteHelperAcc(helper);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> DeleteHelperAccAsync(MusorWpf.ServiceData.logger helper) {
            return base.Channel.DeleteHelperAccAsync(helper);
        }
        
        public MusorWpf.ServiceData.SendIndfo RemoveCodeHelper(MusorWpf.ServiceData.logger helper) {
            return base.Channel.RemoveCodeHelper(helper);
        }
        
        public System.Threading.Tasks.Task<MusorWpf.ServiceData.SendIndfo> RemoveCodeHelperAsync(MusorWpf.ServiceData.logger helper) {
            return base.Channel.RemoveCodeHelperAsync(helper);
        }
    }
}
